if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="individual-3";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import graph;
unitsize(4);
draw((0, 0) -- (16, 0) -- (16, 18) -- (0, 18) -- cycle);
draw((5, 5) -- (8, 9));
draw((5, 5) -- (5, 0));
draw((5, 5) -- (0, 5));
draw((0, 9) -- (8, 9) -- (8, 0));
filldraw((5, 5) -- (8, 5) -- (8, 9) -- cycle, grey);
draw(Circle((5, 5), 5));
draw(Circle((11, 13), 5));
label("8", (4, 0), S);
label("9", (0, 4.5), W);
