if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="individual-1";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

unitsize(10);
pair A = (0, 0), B = (0, 6), C = (4, 6), D = (4, 4), E= (6, 4), F = (6, 5), G = (8, 5), H = (8, 4), I = (10, 4), J = (10, 0);
draw(A--B--C--D--E--F--G--H--I--J--cycle);
label("A", A, S);
label("B", B, N);
label("C", C, N);
label("D", D, S);
label("E", E, S);
label("F", F, N);
label("G", G, N);
label("H", H, S);
label("I", I, N);
label("J", J, S);
